// GENERATED by tool/arcade/gen_registry.py — do not edit by hand.
import 'engine/sfx.dart';
import 'games/g001.dart';
import 'games/g002.dart';
import 'games/g003.dart';
import 'games/g004.dart';
import 'games/g005.dart';
import 'games/g006.dart';
import 'games/g007.dart';
import 'games/g008.dart';
import 'games/g009.dart';
import 'games/g010.dart';
import 'games/g011.dart';
import 'games/g012.dart';
import 'games/g013.dart';
import 'games/g014.dart';
import 'games/g015.dart';
import 'games/g016.dart';
import 'games/g017.dart';
import 'games/g018.dart';
import 'games/g019.dart';
import 'games/g020.dart';
import 'games/g021.dart';
import 'games/g022.dart';
import 'games/g023.dart';
import 'games/g024.dart';
import 'games/g025.dart';
import 'games/g026.dart';
import 'games/g027.dart';
import 'games/g028.dart';
import 'games/g029.dart';
import 'games/g030.dart';
import 'games/g031.dart';
import 'games/g032.dart';
import 'games/g033.dart';
import 'games/g034.dart';
import 'games/g035.dart';
import 'games/g036.dart';
import 'games/g037.dart';
import 'games/g038.dart';
import 'games/g039.dart';
import 'games/g040.dart';
import 'games/g041.dart';
import 'games/g042.dart';
import 'games/g043.dart';
import 'games/g044.dart';
import 'games/g045.dart';
import 'games/g046.dart';
import 'games/g047.dart';
import 'games/g048.dart';
import 'games/g049.dart';
import 'games/g050.dart';
import 'games/g051.dart';
import 'games/g052.dart';
import 'games/g053.dart';
import 'games/g054.dart';
import 'games/g055.dart';
import 'games/g056.dart';
import 'games/g057.dart';
import 'games/g058.dart';
import 'games/g059.dart';
import 'games/g060.dart';
import 'games/g061.dart';
import 'games/g062.dart';
import 'games/g063.dart';
import 'games/g064.dart';
import 'games/g065.dart';
import 'games/g066.dart';
import 'games/g067.dart';
import 'games/g068.dart';
import 'games/g069.dart';
import 'games/g070.dart';
import 'games/g071.dart';
import 'games/g072.dart';
import 'games/g073.dart';
import 'games/g074.dart';
import 'games/g075.dart';
import 'games/g076.dart';
import 'games/g077.dart';
import 'games/g078.dart';
import 'games/g079.dart';
import 'games/g080.dart';
import 'games/g081.dart';
import 'games/g082.dart';
import 'games/g083.dart';
import 'games/g084.dart';
import 'games/g085.dart';
import 'games/g086.dart';
import 'games/g087.dart';
import 'games/g088.dart';
import 'games/g089.dart';
import 'games/g090.dart';
import 'games/g091.dart';
import 'games/g092.dart';
import 'games/g093.dart';
import 'games/g094.dart';
import 'games/g095.dart';
import 'games/g096.dart';
import 'games/g097.dart';
import 'games/g098.dart';
import 'games/g099.dart';
import 'games/g100.dart';
import 'games/g101.dart';
import 'games/g102.dart';
import 'games/g103.dart';
import 'games/g104.dart';
import 'games/g105.dart';
import 'games/g106.dart';
import 'games/g107.dart';
import 'games/g108.dart';
import 'games/g109.dart';
import 'games/g110.dart';
import 'games/g111.dart';
import 'games/g112.dart';
import 'games/g113.dart';
import 'games/g114.dart';
import 'games/g115.dart';
import 'games/g116.dart';
import 'games/g117.dart';
import 'games/g118.dart';
import 'games/g119.dart';
import 'games/g120.dart';
import 'games/g121.dart';
import 'games/g122.dart';
import 'games/g123.dart';
import 'games/g124.dart';
import 'games/g125.dart';
import 'games/g126.dart';
import 'games/g127.dart';
import 'games/g128.dart';
import 'games/g129.dart';
import 'games/g130.dart';
import 'games/g131.dart';
import 'games/g132.dart';
import 'games/g133.dart';
import 'games/g134.dart';
import 'games/g135.dart';
import 'games/g136.dart';
import 'games/g137.dart';
import 'games/g138.dart';
import 'games/g139.dart';
import 'games/g140.dart';
import 'games/g141.dart';
import 'games/g142.dart';
import 'games/g143.dart';
import 'games/g144.dart';
import 'games/g145.dart';
import 'games/g146.dart';
import 'games/g147.dart';
import 'games/g148.dart';
import 'games/g149.dart';
import 'games/g150.dart';
import 'games/g151.dart';
import 'spec.dart';

const List<GameSpec> allGames = [
  GameSpec(no: 1, cat: GameCat.hyper, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.hyper, duration: 15.0, create: G001.new),
  GameSpec(no: 2, cat: GameCat.hyper, style: ArtStyle.threeD, rarity: Rarity.uncommon, bgm: Bgm.hyper, duration: 20.0, create: G002.new),
  GameSpec(no: 3, cat: GameCat.hyper, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.cute, duration: 20.0, create: G003.new),
  GameSpec(no: 4, cat: GameCat.hyper, style: ArtStyle.threeD, rarity: Rarity.common, bgm: Bgm.hyper, duration: 20.0, create: G004.new),
  GameSpec(no: 5, cat: GameCat.hyper, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.hyper, duration: 20.0, create: G005.new),
  GameSpec(no: 6, cat: GameCat.hyper, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.cute, duration: 14.0, create: G006.new),
  GameSpec(no: 7, cat: GameCat.hyper, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.cute, duration: 14.0, create: G007.new),
  GameSpec(no: 8, cat: GameCat.hyper, style: ArtStyle.vector, rarity: Rarity.uncommon, bgm: Bgm.cute, duration: 25.0, create: G008.new),
  GameSpec(no: 9, cat: GameCat.hyper, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.hyper, duration: 18.0, create: G009.new),
  GameSpec(no: 10, cat: GameCat.hyper, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.lofi, duration: 10.0, create: G010.new),
  GameSpec(no: 11, cat: GameCat.hyper, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.hyper, duration: 16.0, create: G011.new),
  GameSpec(no: 12, cat: GameCat.hyper, style: ArtStyle.threeD, rarity: Rarity.uncommon, bgm: Bgm.hyper, duration: 20.0, create: G012.new),
  GameSpec(no: 13, cat: GameCat.hyper, style: ArtStyle.threeD, rarity: Rarity.uncommon, bgm: Bgm.hyper, duration: 20.0, create: G013.new),
  GameSpec(no: 14, cat: GameCat.hyper, style: ArtStyle.threeD, rarity: Rarity.common, bgm: Bgm.hyper, duration: 18.0, create: G014.new),
  GameSpec(no: 15, cat: GameCat.hyper, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.cute, duration: 20.0, create: G015.new),
  GameSpec(no: 16, cat: GameCat.strategy, style: ArtStyle.vector, rarity: Rarity.superRare, bgm: Bgm.survival, duration: 25.0, create: G016.new),
  GameSpec(no: 17, cat: GameCat.strategy, style: ArtStyle.pixel, rarity: Rarity.uncommon, bgm: Bgm.chip, duration: 25.0, create: G017.new),
  GameSpec(no: 18, cat: GameCat.strategy, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.hyper, duration: 20.0, create: G018.new),
  GameSpec(no: 19, cat: GameCat.strategy, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.survival, duration: 20.0, create: G019.new),
  GameSpec(no: 20, cat: GameCat.strategy, style: ArtStyle.threeD, rarity: Rarity.uncommon, bgm: Bgm.boss, duration: 22.0, create: G020.new),
  GameSpec(no: 21, cat: GameCat.strategy, style: ArtStyle.vector, rarity: Rarity.uncommon, bgm: Bgm.chiprpg, duration: 20.0, create: G021.new),
  GameSpec(no: 22, cat: GameCat.strategy, style: ArtStyle.pixel, rarity: Rarity.common, bgm: Bgm.chip, duration: 20.0, create: G022.new),
  GameSpec(no: 23, cat: GameCat.strategy, style: ArtStyle.vector, rarity: Rarity.uncommon, bgm: Bgm.hyper, duration: 22.0, create: G023.new),
  GameSpec(no: 24, cat: GameCat.strategy, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.lofi, duration: 22.0, create: G024.new),
  GameSpec(no: 25, cat: GameCat.strategy, style: ArtStyle.pixel, rarity: Rarity.uncommon, bgm: Bgm.chip, duration: 24.0, create: G025.new),
  GameSpec(no: 26, cat: GameCat.strategy, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.sports, duration: 18.0, create: G026.new),
  GameSpec(no: 27, cat: GameCat.strategy, style: ArtStyle.neon, rarity: Rarity.uncommon, bgm: Bgm.space, duration: 22.0, create: G027.new),
  GameSpec(no: 28, cat: GameCat.strategy, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.boss, duration: 22.0, create: G028.new),
  GameSpec(no: 29, cat: GameCat.strategy, style: ArtStyle.vector, rarity: Rarity.uncommon, bgm: Bgm.boss, duration: 24.0, create: G029.new),
  GameSpec(no: 30, cat: GameCat.strategy, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.cute, duration: 16.0, create: G030.new),
  GameSpec(no: 31, cat: GameCat.tycoon, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.tycoon, duration: 24.0, create: G031.new),
  GameSpec(no: 32, cat: GameCat.tycoon, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.tycoon, duration: 20.0, create: G032.new),
  GameSpec(no: 33, cat: GameCat.tycoon, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.tycoon, duration: 18.0, create: G033.new),
  GameSpec(no: 34, cat: GameCat.tycoon, style: ArtStyle.vector, rarity: Rarity.uncommon, bgm: Bgm.tycoon, duration: 22.0, create: G034.new),
  GameSpec(no: 35, cat: GameCat.tycoon, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.lofi, duration: 14.0, create: G035.new),
  GameSpec(no: 36, cat: GameCat.tycoon, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.tycoon, duration: 22.0, create: G036.new),
  GameSpec(no: 37, cat: GameCat.tycoon, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.tycoon, duration: 20.0, create: G037.new),
  GameSpec(no: 38, cat: GameCat.tycoon, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.tycoon, duration: 20.0, create: G038.new),
  GameSpec(no: 39, cat: GameCat.tycoon, style: ArtStyle.pixel, rarity: Rarity.uncommon, bgm: Bgm.party, duration: 24.0, create: G039.new),
  GameSpec(no: 40, cat: GameCat.tycoon, style: ArtStyle.pixel, rarity: Rarity.common, bgm: Bgm.chip, duration: 22.0, create: G040.new),
  GameSpec(no: 41, cat: GameCat.tycoon, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.tycoon, duration: 14.0, create: G041.new),
  GameSpec(no: 42, cat: GameCat.tycoon, style: ArtStyle.vector, rarity: Rarity.uncommon, bgm: Bgm.tycoon, duration: 22.0, create: G042.new),
  GameSpec(no: 43, cat: GameCat.tycoon, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.lofi, duration: 20.0, create: G043.new),
  GameSpec(no: 44, cat: GameCat.tycoon, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.lofi, duration: 18.0, create: G044.new),
  GameSpec(no: 45, cat: GameCat.tycoon, style: ArtStyle.vector, rarity: Rarity.uncommon, bgm: Bgm.tycoon, duration: 22.0, create: G045.new),
  GameSpec(no: 46, cat: GameCat.party, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.party, duration: 10.0, create: G046.new),
  GameSpec(no: 47, cat: GameCat.party, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.party, duration: 14.0, create: G047.new),
  GameSpec(no: 48, cat: GameCat.party, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.party, duration: 10.0, create: G048.new),
  GameSpec(no: 49, cat: GameCat.party, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.party, duration: 14.0, create: G049.new),
  GameSpec(no: 50, cat: GameCat.party, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.party, duration: 14.0, create: G050.new),
  GameSpec(no: 51, cat: GameCat.party, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.party, duration: 12.0, create: G051.new),
  GameSpec(no: 52, cat: GameCat.party, style: ArtStyle.neon, rarity: Rarity.common, bgm: Bgm.micro, duration: 16.0, create: G052.new),
  GameSpec(no: 53, cat: GameCat.party, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.party, duration: 14.0, create: G053.new),
  GameSpec(no: 54, cat: GameCat.party, style: ArtStyle.vector, rarity: Rarity.superRare, bgm: Bgm.party, duration: 25.0, create: G054.new),
  GameSpec(no: 55, cat: GameCat.party, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.party, duration: 14.0, create: G055.new),
  GameSpec(no: 56, cat: GameCat.party, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.casino, duration: 14.0, create: G056.new),
  GameSpec(no: 57, cat: GameCat.party, style: ArtStyle.threeD, rarity: Rarity.uncommon, bgm: Bgm.party, duration: 20.0, create: G057.new),
  GameSpec(no: 58, cat: GameCat.party, style: ArtStyle.threeD, rarity: Rarity.uncommon, bgm: Bgm.party, duration: 20.0, create: G058.new),
  GameSpec(no: 59, cat: GameCat.party, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.party, duration: 12.0, create: G059.new),
  GameSpec(no: 60, cat: GameCat.party, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.party, duration: 14.0, create: G060.new),
  GameSpec(no: 61, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 5.0, create: G061.new),
  GameSpec(no: 62, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 5.0, create: G062.new),
  GameSpec(no: 63, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 5.0, create: G063.new),
  GameSpec(no: 64, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 5.0, create: G064.new),
  GameSpec(no: 65, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 5.0, create: G065.new),
  GameSpec(no: 66, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 5.0, create: G066.new),
  GameSpec(no: 67, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 5.0, create: G067.new),
  GameSpec(no: 68, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 5.0, create: G068.new),
  GameSpec(no: 69, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 5.0, create: G069.new),
  GameSpec(no: 70, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 5.0, create: G070.new),
  GameSpec(no: 71, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 6.0, create: G071.new),
  GameSpec(no: 72, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 5.0, create: G072.new),
  GameSpec(no: 73, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 5.0, create: G073.new),
  GameSpec(no: 74, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 6.0, create: G074.new),
  GameSpec(no: 75, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 5.0, create: G075.new),
  GameSpec(no: 76, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 5.0, create: G076.new),
  GameSpec(no: 77, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 5.0, create: G077.new),
  GameSpec(no: 78, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 6.0, create: G078.new),
  GameSpec(no: 79, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 6.0, create: G079.new),
  GameSpec(no: 80, cat: GameCat.micro, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 5.0, create: G080.new),
  GameSpec(no: 81, cat: GameCat.retro, style: ArtStyle.pixel, rarity: Rarity.uncommon, bgm: Bgm.chip, duration: 20.0, create: G081.new),
  GameSpec(no: 82, cat: GameCat.retro, style: ArtStyle.pixel, rarity: Rarity.common, bgm: Bgm.chip, duration: 20.0, create: G082.new),
  GameSpec(no: 83, cat: GameCat.retro, style: ArtStyle.pixel, rarity: Rarity.common, bgm: Bgm.chip, duration: 22.0, create: G083.new),
  GameSpec(no: 84, cat: GameCat.retro, style: ArtStyle.pixel, rarity: Rarity.common, bgm: Bgm.chip, duration: 20.0, create: G084.new),
  GameSpec(no: 85, cat: GameCat.retro, style: ArtStyle.pixel, rarity: Rarity.uncommon, bgm: Bgm.chiprpg, duration: 24.0, create: G085.new),
  GameSpec(no: 86, cat: GameCat.retro, style: ArtStyle.pixel, rarity: Rarity.uncommon, bgm: Bgm.chip, duration: 22.0, create: G086.new),
  GameSpec(no: 87, cat: GameCat.retro, style: ArtStyle.pixel, rarity: Rarity.uncommon, bgm: Bgm.boss, duration: 20.0, create: G087.new),
  GameSpec(no: 88, cat: GameCat.retro, style: ArtStyle.pixel, rarity: Rarity.common, bgm: Bgm.lofi, duration: 20.0, create: G088.new),
  GameSpec(no: 89, cat: GameCat.retro, style: ArtStyle.pixel, rarity: Rarity.common, bgm: Bgm.chip, duration: 20.0, create: G089.new),
  GameSpec(no: 90, cat: GameCat.retro, style: ArtStyle.pixel, rarity: Rarity.uncommon, bgm: Bgm.synth, duration: 22.0, create: G090.new),
  GameSpec(no: 91, cat: GameCat.retro, style: ArtStyle.pixel, rarity: Rarity.common, bgm: Bgm.chip, duration: 20.0, create: G091.new),
  GameSpec(no: 92, cat: GameCat.retro, style: ArtStyle.pixel, rarity: Rarity.common, bgm: Bgm.chip, duration: 24.0, create: G092.new),
  GameSpec(no: 93, cat: GameCat.retro, style: ArtStyle.pixel, rarity: Rarity.common, bgm: Bgm.chip, duration: 18.0, create: G093.new),
  GameSpec(no: 94, cat: GameCat.retro, style: ArtStyle.pixel, rarity: Rarity.common, bgm: Bgm.chip, duration: 18.0, create: G094.new),
  GameSpec(no: 95, cat: GameCat.retro, style: ArtStyle.pixel, rarity: Rarity.uncommon, bgm: Bgm.chiprpg, duration: 18.0, create: G095.new),
  GameSpec(no: 96, cat: GameCat.threeD, style: ArtStyle.threeD, rarity: Rarity.uncommon, bgm: Bgm.sports, duration: 18.0, create: G096.new),
  GameSpec(no: 97, cat: GameCat.threeD, style: ArtStyle.threeD, rarity: Rarity.common, bgm: Bgm.sports, duration: 16.0, create: G097.new),
  GameSpec(no: 98, cat: GameCat.threeD, style: ArtStyle.threeD, rarity: Rarity.uncommon, bgm: Bgm.lofi, duration: 22.0, create: G098.new),
  GameSpec(no: 99, cat: GameCat.threeD, style: ArtStyle.threeD, rarity: Rarity.uncommon, bgm: Bgm.synth, duration: 20.0, create: G099.new),
  GameSpec(no: 100, cat: GameCat.threeD, style: ArtStyle.threeD, rarity: Rarity.superRare, bgm: Bgm.synth, duration: 24.0, create: G100.new),
  GameSpec(no: 101, cat: GameCat.threeD, style: ArtStyle.threeD, rarity: Rarity.superRare, bgm: Bgm.spooky, duration: 25.0, create: G101.new),
  GameSpec(no: 102, cat: GameCat.threeD, style: ArtStyle.threeD, rarity: Rarity.common, bgm: Bgm.casino, duration: 14.0, create: G102.new),
  GameSpec(no: 103, cat: GameCat.threeD, style: ArtStyle.threeD, rarity: Rarity.common, bgm: Bgm.cute, duration: 20.0, create: G103.new),
  GameSpec(no: 104, cat: GameCat.threeD, style: ArtStyle.threeD, rarity: Rarity.common, bgm: Bgm.sports, duration: 18.0, create: G104.new),
  GameSpec(no: 105, cat: GameCat.threeD, style: ArtStyle.threeD, rarity: Rarity.uncommon, bgm: Bgm.lofi, duration: 20.0, create: G105.new),
  GameSpec(no: 106, cat: GameCat.threeD, style: ArtStyle.threeD, rarity: Rarity.uncommon, bgm: Bgm.space, duration: 20.0, create: G106.new),
  GameSpec(no: 107, cat: GameCat.threeD, style: ArtStyle.threeD, rarity: Rarity.uncommon, bgm: Bgm.boss, duration: 18.0, create: G107.new),
  GameSpec(no: 108, cat: GameCat.threeD, style: ArtStyle.threeD, rarity: Rarity.common, bgm: Bgm.lofi, duration: 18.0, create: G108.new),
  GameSpec(no: 109, cat: GameCat.gacha, style: ArtStyle.neon, rarity: Rarity.superRare, bgm: Bgm.casino, duration: 20.0, create: G109.new),
  GameSpec(no: 110, cat: GameCat.gacha, style: ArtStyle.neon, rarity: Rarity.uncommon, bgm: Bgm.casino, duration: 18.0, create: G110.new),
  GameSpec(no: 111, cat: GameCat.gacha, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.casino, duration: 14.0, create: G111.new),
  GameSpec(no: 112, cat: GameCat.gacha, style: ArtStyle.neon, rarity: Rarity.uncommon, bgm: Bgm.casino, duration: 18.0, create: G112.new),
  GameSpec(no: 113, cat: GameCat.gacha, style: ArtStyle.neon, rarity: Rarity.common, bgm: Bgm.casino, duration: 14.0, create: G113.new),
  GameSpec(no: 114, cat: GameCat.gacha, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.casino, duration: 12.0, create: G114.new),
  GameSpec(no: 115, cat: GameCat.gacha, style: ArtStyle.neon, rarity: Rarity.uncommon, bgm: Bgm.casino, duration: 20.0, create: G115.new),
  GameSpec(no: 116, cat: GameCat.gacha, style: ArtStyle.vector, rarity: Rarity.uncommon, bgm: Bgm.casino, duration: 20.0, create: G116.new),
  GameSpec(no: 117, cat: GameCat.gacha, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.casino, duration: 18.0, create: G117.new),
  GameSpec(no: 118, cat: GameCat.gacha, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.casino, duration: 14.0, create: G118.new),
  GameSpec(no: 119, cat: GameCat.rpg, style: ArtStyle.vector, rarity: Rarity.uncommon, bgm: Bgm.chiprpg, duration: 20.0, create: G119.new),
  GameSpec(no: 120, cat: GameCat.rpg, style: ArtStyle.vector, rarity: Rarity.uncommon, bgm: Bgm.space, duration: 20.0, create: G120.new),
  GameSpec(no: 121, cat: GameCat.rpg, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.chiprpg, duration: 20.0, create: G121.new),
  GameSpec(no: 122, cat: GameCat.rpg, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.chiprpg, duration: 20.0, create: G122.new),
  GameSpec(no: 123, cat: GameCat.rpg, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.cute, duration: 20.0, create: G123.new),
  GameSpec(no: 124, cat: GameCat.rpg, style: ArtStyle.vector, rarity: Rarity.superRare, bgm: Bgm.boss, duration: 25.0, create: G124.new),
  GameSpec(no: 125, cat: GameCat.rpg, style: ArtStyle.vector, rarity: Rarity.uncommon, bgm: Bgm.boss, duration: 20.0, create: G125.new),
  GameSpec(no: 126, cat: GameCat.rpg, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.cute, duration: 20.0, create: G126.new),
  GameSpec(no: 127, cat: GameCat.rpg, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.spooky, duration: 18.0, create: G127.new),
  GameSpec(no: 128, cat: GameCat.rpg, style: ArtStyle.vector, rarity: Rarity.uncommon, bgm: Bgm.cute, duration: 16.0, create: G128.new),
  GameSpec(no: 129, cat: GameCat.puzzle, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.cute, duration: 24.0, create: G129.new),
  GameSpec(no: 130, cat: GameCat.puzzle, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.lofi, duration: 24.0, create: G130.new),
  GameSpec(no: 131, cat: GameCat.puzzle, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.lofi, duration: 20.0, create: G131.new),
  GameSpec(no: 132, cat: GameCat.puzzle, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.micro, duration: 14.0, create: G132.new),
  GameSpec(no: 133, cat: GameCat.puzzle, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.lofi, duration: 22.0, create: G133.new),
  GameSpec(no: 134, cat: GameCat.puzzle, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.hyper, duration: 24.0, create: G134.new),
  GameSpec(no: 135, cat: GameCat.meta, style: ArtStyle.vector, rarity: Rarity.uncommon, bgm: Bgm.micro, duration: 16.0, create: G135.new),
  GameSpec(no: 136, cat: GameCat.puzzle, style: ArtStyle.pixel, rarity: Rarity.common, bgm: Bgm.chip, duration: 24.0, create: G136.new),
  GameSpec(no: 137, cat: GameCat.sports, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.sports, duration: 16.0, create: G137.new),
  GameSpec(no: 138, cat: GameCat.sports, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.sports, duration: 18.0, create: G138.new),
  GameSpec(no: 139, cat: GameCat.sports, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.sports, duration: 16.0, create: G139.new),
  GameSpec(no: 140, cat: GameCat.sports, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.sports, duration: 14.0, create: G140.new),
  GameSpec(no: 141, cat: GameCat.sports, style: ArtStyle.threeD, rarity: Rarity.uncommon, bgm: Bgm.sports, duration: 20.0, create: G141.new),
  GameSpec(no: 142, cat: GameCat.sports, style: ArtStyle.vector, rarity: Rarity.uncommon, bgm: Bgm.boss, duration: 20.0, create: G142.new),
  GameSpec(no: 143, cat: GameCat.asmr, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.lofi, duration: 18.0, create: G143.new),
  GameSpec(no: 144, cat: GameCat.asmr, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.cute, duration: 20.0, create: G144.new),
  GameSpec(no: 145, cat: GameCat.asmr, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.lofi, duration: 18.0, create: G145.new),
  GameSpec(no: 146, cat: GameCat.asmr, style: ArtStyle.vector, rarity: Rarity.common, bgm: Bgm.lofi, duration: 14.0, create: G146.new),
  GameSpec(no: 147, cat: GameCat.meta, style: ArtStyle.vector, rarity: Rarity.uncommon, bgm: Bgm.micro, duration: 16.0, create: G147.new),
  GameSpec(no: 148, cat: GameCat.meta, style: ArtStyle.vector, rarity: Rarity.uncommon, bgm: Bgm.micro, duration: 14.0, create: G148.new),
  GameSpec(no: 149, cat: GameCat.meta, style: ArtStyle.pixel, rarity: Rarity.uncommon, bgm: Bgm.spooky, duration: 18.0, create: G149.new),
  GameSpec(no: 150, cat: GameCat.meta, style: ArtStyle.vector, rarity: Rarity.superRare, bgm: Bgm.hyper, duration: 16.0, create: G150.new),
  GameSpec(no: 151, cat: GameCat.secret, style: ArtStyle.pixel, rarity: Rarity.secret, bgm: Bgm.secret, duration: 40.0, create: G151.new),
];

final Map<String, GameSpec> gamesById = {for (final g in allGames) g.id: g};
