"""Localization pipeline.

  python tool/l10n/gen_l10n.py export   # writes tool/l10n/source.json (en + ja + words)
  python tool/l10n/gen_l10n.py build    # tool/l10n/<code>.json -> lib/l10n/**/<code>.dart + tables.dart

Translation JSON format (tool/l10n/<code>.json):
  {"ui": {key: text}, "games": {"1": [title, verb, hook], ...}, "words": {key: text}}
Missing entries fall back to English at runtime.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
L10N = os.path.join(ROOT, 'lib', 'l10n')
TOOL = os.path.join(ROOT, 'tool', 'l10n')
CODES = ['en', 'ja', 'zh', 'zh_TW', 'ko', 'es', 'fr', 'de', 'pt', 'ru', 'it', 'hi', 'bn', 'ar', 'ur', 'fa', 'id', 'tr', 'vi', 'th']


def dart_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$').replace('\n', '\\n') + "'"


def ident(code):
    return ''.join(p.capitalize() for p in code.split('_'))


def parse_ui(path):
    txt = open(path, encoding='utf-8').read()
    out = {}
    for m in re.finditer(r"^\s*'([a-zA-Z0-9_]+)':\s*(['\"])(.*?)\2,\s*$", txt, re.M):
        v = m.group(3)
        if m.group(2) == "'":
            v = v.replace("\\'", "'")
        out[m.group(1)] = v.replace('\\$', '$')
    return out


def parse_games(path):
    txt = open(path, encoding='utf-8').read()
    out = {}
    for m in re.finditer(r"^\s*(\d+): \[(.*)\],\s*$", txt, re.M):
        parts = re.findall(r"'((?:[^'\\]|\\.)*)'", m.group(2))
        out[m.group(1)] = [p.replace("\\'", "'").replace('\\$', '$') for p in parts]
    return out


def collect_words():
    """All host.tr('key', 'English') uses across games."""
    words = {}
    gdir = os.path.join(ROOT, 'lib', 'arcade', 'games')
    pat = re.compile(r"""\.tr\(\s*'([a-z0-9_]+)'\s*,\s*(['"])(.*?)\2\s*\)""", re.S)
    for f in sorted(os.listdir(gdir)):
        txt = open(os.path.join(gdir, f), encoding='utf-8').read()
        for m in pat.finditer(txt):
            words.setdefault(m.group(1), m.group(3).replace("\\'", "'"))
    words.setdefault('score', 'Score')
    return words


def export():
    src = {
        'ui_en': parse_ui(os.path.join(L10N, 'ui', 'en.dart')),
        'ui_ja': parse_ui(os.path.join(L10N, 'ui', 'ja.dart')),
        'games_en': parse_games(os.path.join(L10N, 'games', 'en.dart')),
        'games_ja': parse_games(os.path.join(L10N, 'games', 'ja.dart')),
        'words_en': collect_words(),
    }
    os.makedirs(TOOL, exist_ok=True)
    with open(os.path.join(TOOL, 'source.json'), 'w', encoding='utf-8') as f:
        json.dump(src, f, ensure_ascii=False, indent=1)
    print('ui', len(src['ui_en']), 'games', len(src['games_en']), 'words', len(src['words_en']))


def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(content)


def build():
    have_ui, have_games, have_words = ['en', 'ja'], ['en', 'ja'], []
    for code in CODES:
        p = os.path.join(TOOL, code + '.json')
        if not os.path.exists(p):
            continue
        data = json.load(open(p, encoding='utf-8'))
        I = ident(code)
        if data.get('ui') and code not in ('en',):
            lines = ['// GENERATED by tool/l10n/gen_l10n.py from tool/l10n/%s.json' % code,
                     'const Map<String, String> ui%s = {' % I]
            for k, v in data['ui'].items():
                lines.append('  %s: %s,' % (dart_str(k), dart_str(v)))
            lines.append('};\n')
            write(os.path.join(L10N, 'ui', code.lower() + '.dart'), '\n'.join(lines))
            if code not in have_ui:
                have_ui.append(code)
        if data.get('games') and code not in ('en',):
            lines = ['// GENERATED by tool/l10n/gen_l10n.py from tool/l10n/%s.json' % code,
                     'const Map<int, List<String>> gameTexts%s = {' % I]
            for k in sorted(data['games'], key=int):
                v = data['games'][k]
                if len(v) != 3:
                    continue
                lines.append('  %s: [%s],' % (int(k), ', '.join(dart_str(x) for x in v)))
            lines.append('};\n')
            write(os.path.join(L10N, 'games', code.lower() + '.dart'), '\n'.join(lines))
            if code not in have_games:
                have_games.append(code)
        if data.get('words'):
            lines = ['// GENERATED by tool/l10n/gen_l10n.py from tool/l10n/%s.json' % code,
                     'const Map<String, String> words%s = {' % I]
            for k, v in data['words'].items():
                lines.append('  %s: %s,' % (dart_str(k), dart_str(v)))
            lines.append('};\n')
            write(os.path.join(L10N, 'words', code.lower() + '.dart'), '\n'.join(lines))
            have_words.append(code)

    imp = []
    for c in have_games:
        imp.append("import 'games/%s.dart';" % c.lower())
    for c in have_ui:
        imp.append("import 'ui/%s.dart';" % c.lower())
    for c in have_words:
        imp.append("import 'words/%s.dart';" % c.lower())
    out = ['// GENERATED by tool/l10n/gen_l10n.py. Languages without a table fall back to English.']
    out += sorted(imp)
    out.append('')
    out.append('const Map<String, Map<String, String>> uiTables = {')
    out += ["  '%s': ui%s," % (c, ident(c)) for c in have_ui]
    out.append('};\n')
    out.append('const Map<String, Map<int, List<String>>> gameTables = {')
    out += ["  '%s': gameTexts%s," % (c, ident(c)) for c in have_games]
    out.append('};\n')
    out.append('const Map<String, Map<String, String>> wordTables = {')
    out += ["  '%s': words%s," % (c, ident(c)) for c in have_words]
    out.append('};\n')
    write(os.path.join(L10N, 'tables.dart'), '\n'.join(out))
    print('ui:', have_ui)
    print('games:', have_games)
    print('words:', have_words)


if __name__ == '__main__':
    {'export': export, 'build': build}[sys.argv[1] if len(sys.argv) > 1 else 'build']()
