/// Every sound effect and music loop available to mini-games.
///
/// Files live in `assets/audio/sfx/<name>.mp3` and `assets/audio/bgm/<name>.mp3`
/// and are generated by `tool/audio/synth.py`. Use these constants instead of
/// raw strings so a typo fails at compile time.
abstract final class Sfx {
  // UI
  static const tap = 'tap';
  static const select = 'select';
  static const back = 'back';
  static const open = 'open';
  static const whoosh = 'whoosh';
  static const swipe = 'swipe';
  static const notify = 'notify';
  static const typing = 'typing';

  // Rewards / positive
  static const coin = 'coin';
  static const coins = 'coins';
  static const cash = 'cash';
  static const gem = 'gem';
  static const pickup = 'pickup';
  static const powerup = 'powerup';
  static const levelup = 'levelup';
  static const correct = 'correct';
  static const perfect = 'perfect';
  static const star = 'star';
  static const sparkle = 'sparkle';
  static const magic = 'magic';
  static const ding = 'ding';
  static const bell = 'bell';
  static const combo = 'combo'; // pitch it up with rate: for chains

  // Negative
  static const wrong = 'wrong';
  static const buzzer = 'buzzer';
  static const hurt = 'hurt';
  static const oops = 'oops';
  static const glass = 'glass';
  static const crack = 'crack';

  // Impacts
  static const hit = 'hit';
  static const hitHeavy = 'hit_heavy';
  static const punch = 'punch';
  static const slap = 'slap';
  static const thud = 'thud';
  static const bounce = 'bounce';
  static const boing = 'boing';
  static const squish = 'squish';
  static const splat = 'splat';
  static const pop = 'pop';
  static const bubble = 'bubble';
  static const clang = 'clang';
  static const explode = 'explode';
  static const explodeSmall = 'explode_small';
  static const crash = 'crash';

  // Actions
  static const jump = 'jump';
  static const land = 'land';
  static const shoot = 'shoot';
  static const laser = 'laser';
  static const throwIt = 'throw';
  static const swing = 'swing';
  static const slash = 'slash';
  static const arrow = 'arrow';
  static const click = 'click';
  static const tick = 'tick';
  static const beep = 'beep';
  static const scan = 'scan';
  static const stamp = 'stamp';
  static const hammer = 'hammer';
  static const chop = 'chop';
  static const dig = 'dig';
  static const step = 'step';
  static const chomp = 'chomp';
  static const rip = 'rip';
  static const flip = 'flip';
  static const dice = 'dice';

  // Liquid / nature / machines
  static const pour = 'pour';
  static const splash = 'splash';
  static const drip = 'drip';
  static const sizzle = 'sizzle';
  static const fire = 'fire';
  static const wind = 'wind';
  static const spray = 'spray';
  static const scrub = 'scrub';
  static const engine = 'engine';
  static const zap = 'zap';
  static const spin = 'spin';
  static const reelStop = 'reel_stop';
  static const shake = 'shake';
  static const rarityUp = 'rarity_up';
  static const ssr = 'ssr';
  static const drumroll = 'drumroll';
  static const fanfare = 'fanfare';
  static const jingleWin = 'jingle_win';
  static const jingleLose = 'jingle_lose';
  static const count = 'count'; // 3-2-1 beep
  static const go = 'go';
  static const whistle = 'whistle';
  static const cheer = 'cheer';
  static const aww = 'aww';
  static const heartbeat = 'heartbeat';
  static const horror = 'horror';
  static const glitch = 'glitch';

  // 8-bit variants for pixel games
  static const pJump = 'p_jump';
  static const pCoin = 'p_coin';
  static const pShoot = 'p_shoot';
  static const pExplode = 'p_explode';
  static const pHit = 'p_hit';
  static const pPowerup = 'p_powerup';
  static const pSelect = 'p_select';
  static const pDie = 'p_die';

  static const all = <String>[
    tap, select, back, open, whoosh, swipe, notify, typing,
    coin, coins, cash, gem, pickup, powerup, levelup, correct, perfect, star,
    sparkle, magic, ding, bell, combo,
    wrong, buzzer, hurt, oops, glass, crack,
    hit, hitHeavy, punch, slap, thud, bounce, boing, squish, splat, pop,
    bubble, clang, explode, explodeSmall, crash,
    jump, land, shoot, laser, throwIt, swing, slash, arrow, click, tick, beep,
    scan, stamp, hammer, chop, dig, step, chomp, rip, flip, dice,
    pour, splash, drip, sizzle, fire, wind, spray, scrub, engine, zap, spin,
    reelStop, shake, rarityUp, ssr, drumroll, fanfare, jingleWin, jingleLose,
    count, go, whistle, cheer, aww, heartbeat, horror, glitch,
    pJump, pCoin, pShoot, pExplode, pHit, pPowerup, pSelect, pDie,
  ];
}

/// Background music loops. Each game picks one in the registry.
abstract final class Bgm {
  static const menu = 'menu';
  static const rush = 'rush';
  static const hyper = 'hyper';
  static const cute = 'cute';
  static const survival = 'survival';
  static const tycoon = 'tycoon';
  static const party = 'party';
  static const micro = 'micro';
  static const chip = 'chip';
  static const chiprpg = 'chiprpg';
  static const lofi = 'lofi';
  static const casino = 'casino';
  static const spooky = 'spooky';
  static const sports = 'sports';
  static const synth = 'synth';
  static const space = 'space';
  static const boss = 'boss';
  static const secret = 'secret';

  static const all = <String>[
    menu, rush, hyper, cute, survival, tycoon, party, micro, chip, chiprpg,
    lofi, casino, spooky, sports, synth, space, boss, secret,
  ];
}
