"""Generates lib/arcade/registry.dart, stub game files and base game texts
from tool/arcade/lineup.json.  Existing game files are never overwritten.

    python tool/arcade/gen_registry.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
lineup = json.load(open(os.path.join(ROOT, 'tool/arcade/lineup.json'), encoding='utf-8'))
assert len(lineup) == 151, len(lineup)

RARITY = {'C': 'common', 'U': 'uncommon', 'R': 'rare', 'SR': 'superRare', 'S': 'secret'}
STYLE = {'vector': 'vector', 'pixel': 'pixel', 'threeD': 'threeD', 'neon': 'neon'}

games_dir = os.path.join(ROOT, 'lib/arcade/games')
os.makedirs(games_dir, exist_ok=True)

STUB = '''import '../engine/engine.dart';

/// No.{no:03d} {en} — placeholder until the real game lands.
class G{no:03d} extends MiniGame {{
  double _t = 0;

  @override
  void update(double dt) => _t += dt;

  @override
  void onDown(Offset p) => host.win();

  @override
  void render(Canvas c) {{
    D.gradientBg(c, [Pal.purple, Pal.night]);
    D.title(c, 'No.{no:03d}', const Offset(180, 280), size: 48, scale: 1 + .05 * sin(_t * 6));
    D.text(c, 'COMING SOON', const Offset(180, 350), size: 20);
  }}
}}
'''

for g in lineup:
    path = os.path.join(games_dir, 'g%03d.dart' % g['no'])
    if not os.path.exists(path):
        with open(path, 'w', encoding='utf-8', newline='\n') as f:
            f.write(STUB.format(no=g['no'], en=g['en']))

lines = ["// GENERATED by tool/arcade/gen_registry.py — do not edit by hand.",
         "import 'engine/sfx.dart';"]
for g in lineup:
    lines.append("import 'games/g%03d.dart';" % g['no'])
lines.append("import 'spec.dart';")
lines.append('')
lines.append('const List<GameSpec> allGames = [')
for g in lineup:
    lines.append(
        "  GameSpec(no: %d, cat: GameCat.%s, style: ArtStyle.%s, rarity: Rarity.%s, bgm: Bgm.%s, duration: %s, create: G%03d.new),"
        % (g['no'], g['cat'], STYLE[g['style']], RARITY[g['rarity']], g['bgm'], float(g['dur']), g['no']))
lines.append('];')
lines.append('')
lines.append('final Map<String, GameSpec> gamesById = {for (final g in allGames) g.id: g};')
lines.append('')
with open(os.path.join(ROOT, 'lib/arcade/registry.dart'), 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(lines))


def dart_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$') + "'"


os.makedirs(os.path.join(ROOT, 'lib/l10n/games'), exist_ok=True)
for lang, keys in (('en', ('en', 'verbEn', 'hookEn')), ('ja', ('ja', 'verbJa', 'hookJa'))):
    out = ['// Game titles / verbs / hooks for "%s". [title, VERB, hook]' % lang,
           'const Map<int, List<String>> gameTexts%s = {' % lang.capitalize()]
    for g in lineup:
        out.append('  %d: [%s, %s, %s],' % (g['no'], dart_str(g[keys[0]]), dart_str(g[keys[1]]), dart_str(g[keys[2]])))
    out.append('};')
    out.append('')
    with open(os.path.join(ROOT, 'lib/l10n/games/%s.dart' % lang), 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out))

print('ok')
