"""Smoke-test + snapshot only the listed games (compiles nothing else, so
other games being edited in parallel can't break your run).

    python tool/arcade/snap.py 12,13,20-25

Snapshots: build/snaps/gNNN_{0,1,2,3,end}.png
"""
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def parse(arg):
    out = []
    for part in arg.split(','):
        part = part.strip()
        if not part:
            continue
        if '-' in part:
            a, b = part.split('-')
            out.extend(range(int(a), int(b) + 1))
        else:
            out.append(int(part))
    return sorted(set(out))


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    nums = parse(sys.argv[1])
    lineup = {g['no']: g for g in json.load(open(os.path.join(ROOT, 'tool/arcade/lineup.json'), encoding='utf-8'))}
    tag = '_'.join(str(n) for n in nums)[:60]
    gen_dir = os.path.join(ROOT, 'test', 'arcade', 'gen')
    os.makedirs(gen_dir, exist_ok=True)
    path = os.path.join(gen_dir, 'snap_%s_test.dart' % tag)
    lines = ["// GENERATED by tool/arcade/snap.py", "import '../snap_harness.dart';"]
    for n in nums:
        lines.append("import 'package:hitasura_ads/arcade/games/g%03d.dart';" % n)
    lines.append('')
    lines.append('void main() => runSnapTests([')
    for n in nums:
        lines.append('  SnapGame(%d, %s, G%03d.new),' % (n, float(lineup[n]['dur']), n))
    lines.append(']);')
    lines.append('')
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    flutter = os.path.join(os.path.dirname(ROOT), 'flutter', 'bin', 'flutter.bat' if os.name == 'nt' else 'flutter')
    try:
        r = subprocess.run([flutter, 'test', os.path.relpath(path, ROOT)], cwd=ROOT)
    finally:
        try:
            os.remove(path)
        except OSError:
            pass
    sys.exit(r.returncode)


if __name__ == '__main__':
    main()
